apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-chatgpt-auth
  namespace: ai
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/instance: litellm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Mi
