apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
